config/routes.rb
Rails.application.routes.draw do
  get 'books/index'
  get 'books/show'
  get 'countries/index'
  get 'countries/show'
  resources :readers, only: [:index, :show]
  resources :countries, only: [:index, :show]
  resources :books, only: [:index, :show]

  get 'about', to: 'pages#about', as: 'about'
  get 'description',to: 'pages#description',as: 'description'

  root 'readers#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  has_one :reader

  validates :latitude, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :name, presence: true
  validates :isbn, presence: true, uniqueness: true, numericality: { only_integer: true }

  has_many :reads, dependent: :destroy
  has_many :readers, through: :read, dependent: :destroy
end

app/models/country.rb
class Country < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :readers, dependent: :destroy
end

app/models/read.rb
class Read < ApplicationRecord
  belongs_to :reader
  belongs_to :book
end

app/models/reader.rb
class Reader < ApplicationRecord
  validates :name, presence: true

  belongs_to :address
  belongs_to :country

  has_many :reads , dependent: :destroy
  has_many :books, through: :reads, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all()
  end

  def show
    @book = Book.find(params[:id])
  end
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  def index
    @countries = Country.all()
  end

  def show
    @country = Country.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def decription
  end
end

app/controllers/readers_controller.rb
class ReadersController < ApplicationController
  def index
    @readers = Reader.all
  end

  def show
    @reader = Reader.find(params[:id])
    @books_read = Read.where(reader: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/readers_helper.rb
module ReadersHelper
end

app/views/books/index.html.erb
<h3>All Books</h3>
<ul>
<% @books.each do |book|%>
  <li><%=link_to book.name, book %></li>
<%end%>
</ul>

app/views/books/show.html.erb
<h3><%= @book.name%></h3>
<div>
<b>ISBN:</b> <%= @book.isbn%><br>
<b>Author:</b> <%= @book.author%><br>
<b>Published Year:</b> <%= @book.year%><br>

</div>

app/views/countries/index.html.erb
<h3>All Countries</h3>
<ul>
<% @countries.each do |country|%>
  <li><%=link_to country.name, country %></li>
<%end%>
</ul>

app/views/countries/show.html.erb
<h3><%= @country.name%></h3>
<div>
<b>Region:</b> <%= @country.region%><br>
<b>Population:</b> <%= @country.population%><br>
<b>Area:</b> <%= @country.area%><br>
<b>GDP:</b> $<%= @country.gdp%><br>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IntroToRailsProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <header>
      <h1><%= link_to 'BookReaders.com', root_path%></h1>
      <nav class="navbar navbar-expand-sm bg-light">
        <ul class="navbar-nav row">
          <li class="nav-item col-sm btn"><%= link_to 'Home', root_path%></li>
          <li class="nav-item col-sm btn"><%= link_to 'Books', books_path%></li>
          <li class="nav-item col-sm btn"><%= link_to 'Countries', countries_path%></li>
          <li class="nav-item col-sm btn"><%= link_to 'About Us', about_path%></li>
          <li class="nav-item col-sm btn"><%= link_to 'Description', description_path%></li>
        </ul>
      </nav>
    </header>
    <div>
      <%= yield %>
    </div>
    <footer class="pt-4">
      <h5>Copywrong 2018</h5>
    </footer>
  </body>
</html>

app/views/pages/about.html.erb
<h2>About this website</h2>

<p>
  This website is for book readers. It lists a number of readers with their contact information and the books they have read.
</p>

app/views/pages/description.html.erb
<h2>Database description</h2>

<%=link_to "Database ERD", asset_path("/Intro-To-Rails.pdf") , target: "_blank"%>

<p>
  The website uses a couple of open source datasets to populate the database to use the website.

  The website's database has 4 Tables:
  <ul>
    <li>Readers Table</li>
    <li>Books Table</li>
    <li>Addresses Table</li>
    <li>Countries Table</li>
    <li>Reads Table</li>

    <h3>Readers Table</h3>
      <p>
        The Readers Table contains all the readers' information. The columns of this table include Name, phone, email, address and nationality of the reader.
        It is assumed that the reader can only have one nationality and a single place of residence only has one reader.<br>
        <b>Associations</b><br>
          The table has one-to-one association with the address tables and one-to-many association with the country table because one country can
          have many readers.<br>
          This table also has a many-to-many relationship with the Books tables which is resolved using the Reads Table.<br>
        <b>Resource: </b> The data was generated using <a href="https://github.com/stympy/faker">faker gem</a>.
      </p>

    <h3>Books Table</h3>
      <p>
        The Books Table contain information about a limited number of books. The columns include Name, isbn, author and year of the published book.<br>
        <b>Associations</b><br>
          The table has many-to-many association with the Readers Table which is resolved using the Reads table.<br>
        <b>Resource: </b> The dataset was obtained from <a href="https://www.kaggle.com/zygmunt/goodbooks-10k/version/5#books.csv">kaggle datasets.</a>.
      </p>

    <h3>Addresses Table</h3>
      <p>
        This table contains all the addresses. The columns include Full Address, latitude and longitude.<br>
        <b>Associations</b><br>
          Only one-to-one association with the readers table.<br>
        <b>Resource: </b> The data was generated using <a href="https://github.com/stympy/faker">faker gem</a>.
      </p>

  <h3>Countries Table</h3>
      <p>
        This table contains all the countires. The columns include Name, region, area, population and gdp of the country.<br>
        <b>Associations</b><br>
          One-to-many association with the readers table.<br>
        <b>Resource: </b>The dataset was obtained from <a href="https://www.kaggle.com/fernandol/countries-of-the-world">kaggle datasets. https://www.kaggle.com/fernandol/countries-of-the-world
      </p>
  </ul>


</p>

app/views/readers/index.html.erb
<h3>All Readers</h3>
<ul>
<% @readers.each do |reader|%>
  <li><%=link_to reader.name, reader %></li>
<%end%>
</ul>

app/views/readers/show.html.erb
<h3><%= @reader.name%></h3>
<div>
<b>Phone:</b> <%= @reader.phone%><br>
<b>Address:</b> <%= @reader.address.full_address%><br>
<b>Country:</b> <%= link_to @reader.country.name, @reader.country%><br>
<div>
  <b>Books Read:</b> <ul><% @books_read.each do|b|%> <li><%=link_to b.book.name, b.book%></li> <%end%></ul>
</div>

</div>